[package]
name = "roslibrust_controller"
version = "0.1.0"
edition = "2024"

[lints.rust]
warnings = "warn"
dead-code = "warn"

[lints.clippy]
needless_return = "allow"
implicit_return = "forbid"
pedantic = { level = "deny", priority = -1 }
trivially_copy_pass_by_ref = "allow"

[[bin]]
name = "talker"
path = "src/talker.rs"

[[bin]]
name = "draw_circle"
path = "src/draw_circle.rs"

[[bin]]
name = "turtle_controller"
path = "src/turtle_controller.rs"

[dependencies]
roslibrust = { version = "0.20.0", features = ["codegen", "ros1", "roslibrust_ros1"] }
roslibrust_codegen_macro = "0.20.0"
tokio = { version = "1.50.0", features = ["signal"] }
tokio-util = "0.7.18"

[profile.dev]
opt-level = "z"   # Optimize for size ("s" is another option to experiment with)
lto = true        # Enable Link Time Optimization for dead code elimination
codegen-units = 1 # Maximize size reduction, but increases compile time
strip = true      # Automatically strip symbols from the binary
