[package]
name = "rosrust_controller"
version = "0.1.0"
edition = "2024"

[lints.rust]
warnings = "warn"
dead-code = "warn"
unused_imports = "deny"
unused_variables = "deny"

[lints.clippy]
needless_return = "allow"
implicit_return = "forbid"
pedantic = { level = "deny", priority = -1 }
trivially_copy_pass_by_ref = "allow"

[dependencies]
env_logger = "0.11.9"
rosrust = "0.9"
rosrust_msg = "0.1"

[[bin]]
name = "draw_circle"
path = "src/draw_circle.rs"

[[bin]]
name = "draw_square"
path = "src/draw_square.rs"

[[bin]]
name = "pose_subscriber"
path = "src/pose_subscriber.rs"

[[bin]]
name = "talker"
path = "src/talker.rs"

[[bin]]
name = "turtle_controller"
path = "src/turtle_controller.rs"

[profile.dev]
opt-level = "z"   # Optimize for size ("s" is another option to experiment with)
lto = true        # Enable Link Time Optimization for dead code elimination
codegen-units = 1 # Maximize size reduction, but increases compile time
strip = true      # Automatically strip symbols from the binary
